name: Test check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ github.repository_owner == 'noxtton' && secrets.NOXTTON_BOT_PAT || secrets.PAT_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ env.GH_PAT }}
          submodules: recursive

      - name: Configure Git credentials
        run: |
          git config --global --add url."https://${{ env.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "git+ssh://git@github.com/"
          git config --global --add url."https://${{ env.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "git@github.com:"
          git config --global --add url."https://${{ env.GH_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://npm.pkg.github.com"
          scope: "@tetherto"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        env:
          NODE_AUTH_TOKEN: ${{ env.GH_PAT }}

      - name: Extract lingui translations
        run: npm run lingui:extract

      - name: Compile lingui translations
        run: npm run lingui:compile

      - name: Run tests
        run: npm test
